version: '3.8'
services:
  mysql-shard-1:
    image: mysql:8.0
    container_name: mysql-local-shard-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: sid
      MYSQL_PASSWORD: sidpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_shard_1_data:/var/lib/mysql        # persist data across restarts
  mysql-shard-2:
    image: mysql:8.0
    container_name: mysql-local-shard-2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: sid
      MYSQL_PASSWORD: sidpass
    ports:
      - "3308:3306"
    volumes:
      - mysql_shard_2_data:/var/lib/mysql        # persist data across restarts

volumes:
  mysql_shard_1_data:
  mysql_shard_2_data:
